
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/pete/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.16.18-1-MANJARO - x86_64
...
